from typing import Any, Dict, Protocol, Optional, Callable, Awaitable
from datetime import datetime
from uuid import UUID

class UnitOfWork(Protocol):
    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

class SubmissionReadPort(Protocol):
    async def get_submission(self, uow: UnitOfWork, submission_id: UUID) -> Dict[str, Any]: ...

class AnswerMutationPort(Protocol):
    async def save_answers(self, uow: UnitOfWork, submission_id: UUID, answers: list[Dict[str, Any]]) -> None: ...
    async def lock_answers(self, uow: UnitOfWork, submission_id: UUID, locked_at: datetime) -> None: ...

class StagePort(Protocol):
    async def acquire_stage(
        self, uow: UnitOfWork, submission_id: UUID, stage: str, input_fingerprint: str, owner: str, lease_seconds: int
    ) -> Dict[str, Any]: ...

    async def commit_stage(
        self, uow: UnitOfWork, submission_id: UUID, stage: str, input_fingerprint: str, owner: str, fence: int, result: Dict[str, Any]
    ) -> None: ...

class OutboxPort(Protocol):
    async def append_event(self, uow: UnitOfWork, event_type: str, payload: Dict[str, Any]) -> str: ...
    async def acknowledge_event(self, event_id: str, owner: str, fence: int) -> None: ...

class ReviewPort(Protocol):
    async def claim_task(self, uow: UnitOfWork, task_id: UUID, claimant: str, lease_seconds: int) -> Dict[str, Any]: ...
    async def resolve_task(
        self, uow: UnitOfWork, task_id: UUID, expected_version: int, resolution: Dict[str, Any]
    ) -> None: ...
